import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import worksData from './api/worksData.json';

import { LightgalleryProvider, LightgalleryItem } from 'react-lightgallery';
import 'lightgallery.js/dist/css/lightgallery.css';

import styles from '../styles/Home.module.css';
import { Wrapper } from '../styles';

const Home: NextPage = () => {
  const [name, setName] = useState('');

  useEffect(() => {
    const processData = async () => {
      const fetchData = await fetch('./api');
      const dataJson = await fetchData.json();
      const { name } = dataJson;
      setName(name);
    };

    processData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
            {name && <div>Name is {name}</div>}
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div className={styles.grid}>
            <LightgalleryProvider>
              {(worksData || []).map((item, index) => {
                const { thumb, imgs, group } = item;

                const Thumb = (
                  <LightgalleryItem group="any" src={thumb} key={index}>
                    <img src={thumb} style={{ maxWidth: '200px' }} />
                  </LightgalleryItem>
                );

                const MainImgs = Object.values(imgs).map((imgUrl, index) => {
                  return (
                    <LightgalleryItem group={group} src={imgUrl} key={index}>
                      <img src={imgUrl} style={{ maxWidth: '500px' }} />
                    </LightgalleryItem>
                  );
                });

                return (
                  <>
                    {Thumb}
                    {MainImgs}
                  </>
                );
              })}
            </LightgalleryProvider>
          </div>
        </main>
      </Wrapper>
      <footer className={styles.footer}></footer>
    </div >
  );
};

export default Home;
