import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import FsLightbox from 'fslightbox-react';
import styles from '../styles/Home.module.css';
import { Wrapper, Title, SubTitle } from '../styles';

const Home: NextPage = () => {
  const [name, setName] = useState('');
  const [worksData, setWorks] = useState([]);

  useEffect(() => {
    const setData = async () => {
      const fetchData = await fetch('./api');
      const dataJson = await fetchData.json();
      const { name, worksData } = dataJson;
      setName(name);
      setWorks(worksData.reverse());
    };

    setData();
  }, []);

  // For lightbox
  const [toggler, setToggler] = useState(false);
  const [productIndex, setProductIndex] = useState(0);
  const onThumbClick = (index: number) => {
    setToggler(!toggler);
    setProductIndex(index);
  };
  const { imgs } = worksData[productIndex] || [];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        {worksData.length > 0 && <main className={styles.main}>
          <Title>
            Michael Zick
          </Title>
          <SubTitle italic>
            React Engineer
          </SubTitle>

          <div className={styles.grid}>
            {worksData.map((item, index) => {
              const { thumb, group } = item;

              return (
                <div onClick={() => onThumbClick(index)} key={index}>
                  <Image src={thumb} width='200px' height='200px' alt={group} className='thumb' />
                </div>
              );
            })}
          </div>
          <FsLightbox
            toggler={toggler}
            sources={imgs}
          />
        </main>}
      </Wrapper>
      <footer className={styles.footer}></footer>
    </div >
  );
};

export default Home;
