import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import FsLightbox from 'fslightbox-react';
import styles from '../styles/Home.module.scss';
import BioBoxContent from '../src/BioBoxContent';
import { Wrapper, Title, SubTitle, LinkBox } from '../styles';

import { scrollMethod } from '../src/helpers';

const Home: NextPage = () => {
  const [worksData, setWorks] = useState([]);

  useEffect(() => {
    const setData = async () => {
      const fetchData = await fetch('./api');
      const dataJson = await fetchData.json();
      const { worksData } = dataJson;
      setWorks(worksData.reverse());
    };

    setData();
  }, []);

  // For lightbox
  const [lightboxController, setLightboxController] = useState({
    toggler: false,
    productIndex: 0
  });

  const onThumbClick = (index: number) => {
    setLightboxController({
      toggler: !lightboxController.toggler,
      productIndex: index
    });
  };

  const { imgs } = worksData[lightboxController.productIndex] || [];

  return (
    <div className={styles.container}>
      <Head>
        <title>Michael Zick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        {worksData.length > 0 && <main className={styles.main}>
          <Title>
            Michael Zick
          </Title>
          <SubTitle>
            UI Engineer
          </SubTitle>

          <LinkBox>
            <a href='https://github.com/michaelzick' target='_blank' rel='noreferrer'>GitHub</a>
            <a href='https://linkedin.com/in/michaelzick' target='_blank' rel='noreferrer'>LinkedIn</a>
            <a href='' onClick={(ev) => {
              ev.preventDefault();
              const element = document.getElementById('about');
              scrollMethod(ev, element);
            }}>About</a>
          </LinkBox>

          <div className={styles.grid}>
            {worksData.map((item, index) => {
              const { thumb, group } = item;

              const Thumb: React.FunctionComponent = () => (
                <div onClick={() => onThumbClick(index)}>
                  <Image src={thumb} width='200px' height='200px' alt={group} className='thumb' />
                </div>
              );

              return (
                <Thumb key={group} />
              );
            })}
          </div>

          <FsLightbox
            toggler={lightboxController.toggler}
            sources={imgs}
            slide={1}
          />

          <BioBoxContent />
        </main>}
      </Wrapper>
      <footer className={styles.footer}></footer>
    </div >
  );
};

export default Home;
